import type { Metadata } from "next";
import { Inter, Coiny } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/desktop/DesktopHeader";
import Providers from "./providers";
import { MobileHeader } from "@/components/mobile/MobileHeader/MobileHeader";
import { Footer } from "@/components/shared/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="hidden md:flex md:justify-center md:w-full">
            <Header></Header>
          </div>

          <div className="w-full md:hidden">
            <MobileHeader></MobileHeader>
          </div>

          {children}

          <div className="mt-auto flex justify-center w-full md:pb-4">
            <Footer></Footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
