import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/desktop/DesktopHeader";
import Providers from "./providers";
import { MobileHeader } from "@/components/mobile/MobileNavBar,tsx/MobileHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="hidden md:flex md:justify-center md:w-full">
            <Header></Header>
          </div>

          <div className="md:hidden">
            <MobileHeader></MobileHeader>
          </div>

          {children}
        </Providers>
      </body>
    </html>
  );
}
